### ISSUE TITLE
Git Extensions not coming in visual studio 2019 extension search

### ISSUE THREAD

**Issue by KamranShahid** [gitextensions/gitextensions.vsix#27]
Git Extensions not coming in visual studio 2019 extension search

**Comment by RussKie** [comment]
VS Marketplace support team has accidentally deleted Henk's profile. They promised to restore it.

**Comment by RussKie** [comment]
I have published the extension under the project's profile. https://marketplace.visualstudio.com/items?itemName=GitExtensionsApp.v341

/cc: @spdr870

**Comment by Shulem** [comment]
> I have published the extension under the project's profile. https://marketplace.visualstudio.com/items?itemName=GitExtensionsApp.v341
> 
> /cc: @spdr870

I'm getting _`We're sorry, the page you requested cannot be found!`_ when clicking the link above,

But I did find the latest version of the extension to download on GitHub 
https://github.com/gitextensions/gitextensions.vsix/releases/download/v3.4.0/GitExtensionsVSIX.3.4.0.7.vsix

**Comment by RussKie** [comment]
Please try again.

**Comment by KamranShahid** [comment]
Now using Git Tools 2019. It seems to have similar functionality
