### ISSUE TITLE
Not compatible with GitExtensions 5

### ISSUE THREAD

**Issue by torbenkohlmeier** [gitextensions/gitextensions.vsix#33]
After updating to GitExtensions 5, I get the following error message when trying to open GitExtensions with the extension:

> This plugin requires Git Extensions to be installed. This application can be downloaded from http://gitextensions.github.io/

**Comment by torbenkohlmeier** [comment]
I was able to fix this by correcting the path in the registry key `Computer\HKEY_CURRENT_USER\Software\GitExtensions\InstallDir`.

**Comment by RussKie** [comment]
v5 is a 64-bit app, and it's installed in "C:\Program Files\GitExtensions" instead of "C:\Program Files (x86)\GitExtensions".

It's noted in the release notes: https://github.com/gitextensions/gitextensions/releases/tag/v5.0.

**Comment by torbenkohlmeier** [comment]
Yes, but I think, the registry key should be updated automatically when updating.

**Comment by RussKie** [comment]
I checked my installation and the registry was updated.... How did you update to v5?

**Comment by torbenkohlmeier** [comment]
I need to use a special feature for running installers with elevated rights which uses another user context. That's probably why the installer didn't update the registry key of my user. So the only solution I could think of would be that GitExtensions itself updates the registry every time it is run.

**Comment by pmiossec** [comment]
> So the only solution I could think of would be that GitExtensions itself updates the registry every time it is run.

At startup it seems to me overkill but when settings are checked:
![image](https://github.com/user-attachments/assets/400a2a16-0ff1-45ab-9b88-2e6285d725ee)

User has just to click on the settings to update it:

![image](https://github.com/user-attachments/assets/7a2e1d31-d536-4417-840f-443df0657b44)


Have a look at attempt done in [#11913](https://github.com/gitextensions/gitextensions/pull/11913)

**Comment by torbenkohlmeier** [comment]
Good idea!
